### ISSUE TITLE
Design a session schema

### ISSUE THREAD

**Issue by juaoose** [muxable/stream-dashboard#16]

**Comment by Leeoku** [comment]
{
account: string 
sessionNumber: integer  
unstableEvents: number  
duraton: integer  
startDate: Date()  
endDate: Date()  
city: string  
country: string  
modem: string   
server: string  
live: boolean  
}

**Comment by KeN095** [comment]
Would adding in modemTemperature be useful? It can help in diagnosing issues/correlating to other factors for stream, but other than that i don't see a use for it.

**Comment by Leeoku** [comment]
i have added also made some revision. Not sure if we need to focus on hardware related stuff or network, my intuition is network

**Comment by chungwwei** [comment]
Probly a userID for filtering purpose? ig it can be the email. We don't want to show all streams, but only those belong to the login user.

**Comment by KeN095** [comment]
> i have added also made some revision. Not sure if we need to focus on hardware related stuff or network, my intuition is network

Focus should be on network but we can collect basic hardware info and make the graph interactive so that when the user clicks on a point on the graph, it can also display the temperature of the modem, if the modem was on, at that point of time, the city and country they were in at that time etc. 

I'll update the doc on where that would go.
